// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AttributeItem: typeof import('./components/attribute-item/AttributeItem.vue')['default']
    ButtonPrimary: typeof import('./components/shared/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./components/shared/ButtonSecondary.vue')['default']
    ComponentCard: typeof import('./components/page-editor/ComponentCard.vue')['default']
    ComponentList: typeof import('./components/page-editor/ComponentList.vue')['default']
    Feature: typeof import('./components/Feature.vue')['default']
    Features: typeof import('./components/Features.vue')['default']
    Heading1: typeof import('./components/shared/Heading1.vue')['default']
    Heading2: typeof import('./components/shared/Heading2.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    IconCarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconCarbonAccessibilityColor: typeof import('~icons/carbon/accessibility-color')['default']
    IconCarbonBookmarkAdd: typeof import('~icons/carbon/bookmark-add')['default']
    IconCarbonSave: typeof import('~icons/carbon/save')['default']
    LabelValue: typeof import('./components/label-value/LabelValue.vue')['default']
    List: typeof import('./components/list/List.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PagePanel: typeof import('./components/page-editor/PagePanel.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
    Title: typeof import('./components/ruler/Title.vue')['default']
  }
}

export { }
